### ISSUE TITLE
Error occurred when executing comfy-kandinsky22-hint-combiner

### ISSUE THREAD

**Issue by Aljnk** [vsevolod-oparin/comfyui-kandinsky22#1]
I am trying the demo workflow - workflow-depth.json
Nothing changes.
I get an error:
<img width="867" alt="Screenshot_2" src="https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/11256478/06e29deb-8bab-41e7-b45c-17ddb8964e59">

```
Error occurred when executing comfy-kandinsky22-hint-combiner:

expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [, ]
```
<img width="626" alt="Screenshot_1" src="https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/11256478/3bf05f48-e145-4135-923b-b14a21828dd9">

Other workflows are working good

**Comment by vsevolod-oparin** [comment]
Hey @Aljnk, thanks for the report. Can you pull the repo and try it again now? I added a fix in aac63d.

**Comment by Aljnk** [comment]
Hi again.
Error does not appear but
I'm not sure, but it's not working properly - 
<img width="496" alt="Screenshot_1" src="https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/11256478/c0bb42d9-b6c8-4179-9878-520dc12994e0">
result must be close to depth, but not

**Comment by vsevolod-oparin** [comment]
Hm, could you show whole pipeline?

**Comment by Aljnk** [comment]
your demo + my photos
do not change anything
![workflow](https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/11256478/733d5670-5d72-464b-9c67-fd7457a931fd)

**Comment by Aljnk** [comment]
maybe change some seeds :)

**Comment by vsevolod-oparin** [comment]
I see. If you didn't rename decoder checkpoint, you are using wrong one. It doesn't support depth hint.
Make sure to use Control Depth decoder: https://huggingface.co/kandinsky-community/kandinsky-2-2-controlnet-depth

**Comment by vsevolod-oparin** [comment]
![313419913-733d5670-5d72-464b-9c67-fd7457a931fd](https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/462138/a0c350db-701b-4d22-a04b-dbc64d7f7939)

**Comment by Aljnk** [comment]
Yes, I renamed - 
I installed your node today:
- https://huggingface.co/kandinsky-community/kandinsky-2-2-decoder
- https://huggingface.co/kandinsky-community/kandinsky-2-2-prior

**Comment by vsevolod-oparin** [comment]
You need
- https://huggingface.co/kandinsky-community/kandinsky-2-2-controlnet-depth

It's another third checkpoint.

**Comment by Aljnk** [comment]
I see :) Thanks a lot!

**Comment by vsevolod-oparin** [comment]
You're welcome!
