### ISSUE TITLE
I put models to './model/checkpoint',but it show wrong path.

### ISSUE THREAD

**Issue by T8star1984** [vsevolod-oparin/comfyui-kandinsky22#2]
![QQ图片20240317135433](https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/161950228/d25b38de-46b3-48a2-a530-a1bf89b51762)

I put models to './model/checkpoint',but it show wrong path.

**Comment by T8star1984** [comment]
![QQ图片20240317160804](https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/161950228/d1a24fea-a723-4b03-ad8f-b6bc91f3eed2)
is it wrong?

**Comment by vsevolod-oparin** [comment]
Yeah, the plugin expects the checkpoints sitting in folders like on HF itself.

![image](https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/462138/09c4b98f-afb3-4754-a141-9e9b8edfd162)

![image](https://github.com/vsevolod-oparin/comfyui-kandinsky22/assets/462138/df1aa830-5c45-4768-8035-b084b3dc561c)

**Comment by T8mars** [comment]
thanks ,let me try

**Comment by T8mars** [comment]
it's perfect,I like this project,thx again

**Comment by vsevolod-oparin** [comment]
Thank you! You're welcome!
